In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import torch

pd.options.display.max_columns = 0

In [2]:
x_2d = [
    t.squeeze() for t in torch.split(torch.arange(0, 12).reshape(3, 2, 2), 1)
]
x_2d

[tensor([[0, 1],
         [2, 3]]),
 tensor([[4, 5],
         [6, 7]]),
 tensor([[ 8,  9],
         [10, 11]])]

In [3]:
x_2d[0].shape

torch.Size([2, 2])

In [4]:
dim0 = torch.stack(x_2d, dim=0)
print(dim0.shape)
dim0

torch.Size([3, 2, 2])


tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]])

In [5]:
dim1 = torch.stack(x_2d, dim=1)
print(dim1.shape)
dim1

torch.Size([2, 3, 2])


tensor([[[ 0,  1],
         [ 4,  5],
         [ 8,  9]],

        [[ 2,  3],
         [ 6,  7],
         [10, 11]]])

In [6]:
dim2 = torch.stack(x_2d, dim=2)
print(dim2.shape)
dim2

torch.Size([2, 2, 3])


tensor([[[ 0,  4,  8],
         [ 1,  5,  9]],

        [[ 2,  6, 10],
         [ 3,  7, 11]]])